### PR TITLE
Pass onBadCertificate handler from connection settings to SecureSocket

### PR DESCRIPTION
**Pull request by jrobindb**
Fixes Issue #56.

I am not sure how to properly add a test for this change.

### CODE REVIEW

**Comment by achilleasa** [comment]
To test this you can modify [this](https://github.com/achilleasa/dart_amqp/blob/master/test/lib/client_test.dart#L118-L126) test to pass a bogus certificate (see a few lines above for how to setup a local rabbit instance to use the local test certs) and verify that `onBadCertificate` gets invoked.

**Comment by achilleasa** [comment]
@jrobindb Any update on adding a test for this PR? I am preparing to push a new release and it would be great to get this PR landed before that.

**Comment by jrobindb** [comment]
> @jrobindb Any update on adding a test for this PR? I am preparing to push a new release and it would be great to get this PR landed before that.

I am sorry, I don't expect to be able to get to it in the foreseeable future.

**Comment by achilleasa** [comment]
No worries. I will append a commit for the tests and land this.

**Comment by achilleasa** [comment]
Closing in favor of #63 which includes this commit plus the missing test.

**Pull request closed without merging**
