### PR TITLE
Add autoDelete flag to channel implementation

### PR DESCRIPTION
**Pull request by HyprUsr**
Add autoDelete flag to channel implementation

### CODE REVIEW

**Comment by achilleasa** [comment]
Is this a rabbitmq-specific interpretation of this flag? 

Section 1.6.2.1 of the AMQP [spec](https://www.rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf) which was used to auto-generate the bindings shows this field as reserved.

**Comment by Jafarili** [comment]
I think it's added in [amqp.0-10](https://www.amqp.org/specification/0-10/amqp-org-download):

Screenshot 2024-05-30 at 15 42 24

**Comment by achilleasa** [comment]
Thanks for the link. This package only supports the 0.9.1 version of the spec so I would rather we did not manipulate fields that are marked reserved in 0.9.1 as this might make servers reject behave unexpectedly (e.g. close the stream with an error).

**Comment by HyprUsr** [comment]
fair enough, so I'll close the PR :)

**Pull request closed without merging**
