### PR TITLE
fix code for Dart-2.5

### PR DESCRIPTION
**Pull request by a14n**
There's a breaking change in Dart-2.5 that requires some code changes like [advised in CHANGELOG](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#core-libraries-1).

### CODE REVIEW

**Comment by a14n** [comment]
CI fixed

**Comment by a14n** [comment]
@achilleasa will it be possible to publish a new version on pub please?

**Comment by natgross** [comment]
In pubspec.yaml  I have:
         dart_amqp: ^0.1.1
So, how do I get the .yaml to pull in the latest fix?
Thanks

**Comment by achilleasa** [comment]
Version 0.1.2 has just been published.

**Comment by a14n** [comment]
Awesome! Thanks!

**Pull request merged**
